# Generated by Django 4.2.23 on 2025-06-30 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_role_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre du Module"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Durée (minutes)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Création"
                    ),
                ),
                (
                    "documentation_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_modules",
                        to="core.documentationcenter",
                        verbose_name="Centre de Documentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module de Formation",
                "verbose_name_plural": "Modules de Formation",
                "ordering": ["title"],
                "unique_together": {("documentation_center", "title")},
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre du Quiz"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "pass_score",
                    models.IntegerField(
                        default=70, verbose_name="Score de Réussite (%)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Création"
                    ),
                ),
                (
                    "training_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="core.trainingmodule",
                        verbose_name="Module de Formation Associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "ordering": ["title"],
                "unique_together": {("training_module", "title")},
            },
        ),
        migrations.CreateModel(
            name="StaffTrainingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de Complétion",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Score obtenu (%)"
                    ),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="Réussi")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="core.quiz",
                        verbose_name="Quiz (optionnel)",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_records",
                        to="core.staff",
                        verbose_name="Membre du Personnel",
                    ),
                ),
                (
                    "training_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="core.trainingmodule",
                        verbose_name="Module de Formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de Formation du Personnel",
                "verbose_name_plural": "Historiques de Formation du Personnel",
                "ordering": ["-completion_date"],
                "unique_together": {
                    ("staff_member", "training_module", "completion_date")
                },
            },
        ),
    ]
