# Generated by Django 4.2.23 on 2025-06-30 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_trainingmodule_quiz_stafftrainingrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivalSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nom de la Série Archivistique"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description de la Série"
                    ),
                ),
                (
                    "creation_date_range",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Période de Création (ex: 1900-1950)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Série Active"),
                ),
                (
                    "documentation_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archival_series",
                        to="core.documentationcenter",
                        verbose_name="Centre de Documentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Série Archivistique",
                "verbose_name_plural": "Séries Archivilistiques",
                "ordering": ["name"],
                "unique_together": {("documentation_center", "name")},
            },
        ),
        migrations.CreateModel(
            name="ArchivalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre du Document"),
                ),
                (
                    "document_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Identifiant du Document",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "creation_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de Création du Document",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Créateur(s) / Auteur(s) d'origine",
                    ),
                ),
                (
                    "physical_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Emplacement Physique (Cote)",
                    ),
                ),
                (
                    "is_digital",
                    models.BooleanField(
                        default=False, verbose_name="Version Numérique Disponible"
                    ),
                ),
                (
                    "digital_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="archives/digital/",
                        verbose_name="Fichier Numérique (PDF, Image, etc.)",
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'Acquisition/Classement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("restricted", "Accès Restreint"),
                            ("damaged", "Endommagé"),
                            ("missing", "Manquant"),
                        ],
                        default="available",
                        max_length=50,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "archival_series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.archivalseries",
                        verbose_name="Série Archivistique",
                    ),
                ),
                (
                    "documentation_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archival_documents",
                        to="core.documentationcenter",
                        verbose_name="Centre de Documentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Archivistique",
                "verbose_name_plural": "Documents Archivilistiques",
                "ordering": ["title"],
                "unique_together": {("documentation_center", "document_id")},
            },
        ),
    ]
