# Generated by Django 4.2.23 on 2025-06-30 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0007_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalizationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(verbose_name="ID de l'Objet"),
                ),
                (
                    "request_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de Demande",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("in_progress", "En cours"),
                            ("quality_check", "Contrôle qualité"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Statut de la Digitalisation",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de Complétion"
                    ),
                ),
                (
                    "digital_file_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        verbose_name="URL du Fichier Numérique Final",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Type de Contenu",
                    ),
                ),
                (
                    "documentation_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digitalization_requests",
                        to="core.documentationcenter",
                        verbose_name="Centre de Documentation",
                    ),
                ),
                (
                    "requested_by_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.staff",
                        verbose_name="Demandé par le personnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de Digitalisation (Nubo)",
                "verbose_name_plural": "Demandes de Digitalisation (Nubo)",
                "ordering": ["-request_date", "status"],
            },
        ),
    ]
