# Generated by Django 4.2.23 on 2025-07-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_activity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["name"],
                "verbose_name": "Activité",
                "verbose_name_plural": "Activités",
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Une description détaillée de l'activité.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(
                help_text="Le nom officiel de l'activité.",
                max_length=255,
                verbose_name="Nom de l'activité",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de début"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planifié"),
                    ("active", "Actif"),
                    ("inactive", "Inactif"),
                    ("completed", "Terminé"),
                    ("suspended", "Suspendu"),
                ],
                default="planned",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
