# Generated by Django 4.2.23 on 2025-07-09 01:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_activity_options_alter_activity_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archivaldocument",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Archival Document",
                "verbose_name_plural": "Archival Documents",
            },
        ),
        migrations.AlterUniqueTogether(
            name="archivaldocument",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="archivaldocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 7, 9, 1, 11, 14, 923181, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="archivaldocument",
            name="file_upload",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="archives/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="archivaldocument",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="archivaldocument",
            name="documentation_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archival_documents",
                to="core.documentationcenter",
            ),
        ),
        migrations.AlterField(
            model_name="archivaldocument",
            name="status",
            field=models.CharField(
                choices=[("public", "Public"), ("confidential", "Confidential")],
                default="confidential",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="archivaldocument",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name="archivaldocument",
            name="acquisition_date",
        ),
        migrations.RemoveField(
            model_name="archivaldocument",
            name="archival_series",
        ),
        migrations.RemoveField(
            model_name="archivaldocument",
            name="creation_date",
        ),
        migrations.RemoveField(
            model_name="archivaldocument",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="archivaldocument",
            name="digital_file",
        ),
        migrations.RemoveField(
            model_name="archivaldocument",
            name="document_id",
        ),
        migrations.RemoveField(
            model_name="archivaldocument",
            name="is_digital",
        ),
        migrations.RemoveField(
            model_name="archivaldocument",
            name="physical_location",
        ),
    ]
