# Generated by Django 4.2.23 on 2025-07-11 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_trainingsubject"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingmodule",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modules",
                to="core.trainingsubject",
                verbose_name="Sujet de Formation",
            ),
        ),
    ]
