# Generated by Django 4.2.23 on 2025-07-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_trainingmodule_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Level 1, Chapter 1", max_length=255
                    ),
                ),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[("video", "Vidéo"), ("text", "Texte")],
                        default="video",
                        max_length=10,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Link to the lesson video.", null=True
                    ),
                ),
                (
                    "text_content",
                    models.TextField(
                        blank=True,
                        help_text="Content for text-based lessons (supports Markdown).",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The order of the lesson in the course (e.g., 1, 2, 3).",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="trainingmodule",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="trainingmodule",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="minimum_age_required",
            field=models.PositiveIntegerField(
                default=10, help_text="Minimum age to access this training."
            ),
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="points_to_pass",
            field=models.PositiveIntegerField(
                default=70,
                help_text="Minimum points required to pass the entire training.",
            ),
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("published", "Publié"),
                    ("archived", "Archivé"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="A thumbnail image for the training course, like on YouTube.",
                null=True,
                upload_to="training_thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="documentation_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_modules",
                to="core.documentationcenter",
            ),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Estimated duration of the training in minutes."
            ),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Is this training currently active and visible to users?",
            ),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_modules",
                to="core.trainingsubject",
            ),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=500)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mc", "Choix Multiple"),
                            ("text", "Réponse textuelle"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=1, help_text="Points awarded for a correct answer."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="training_module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="core.trainingmodule",
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.CharField(max_length=255)),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, help_text="Is this the correct answer?"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.question",
                    ),
                ),
            ],
        ),
    ]
