# Generated by Django 4.2.23 on 2025-07-11 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_lesson_alter_trainingmodule_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Communique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "objective",
                    models.CharField(
                        help_text="A short summary of the message's goal.",
                        max_length=500,
                    ),
                ),
                (
                    "message_body",
                    models.TextField(help_text="The full content of the announcement."),
                ),
                (
                    "publication_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff member who wrote the announcement.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.staff",
                    ),
                ),
                (
                    "documentation_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communiques",
                        to="core.documentationcenter",
                    ),
                ),
                (
                    "target_activities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Send only to staff in these activities. Leave blank to send to all.",
                        to="core.activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communiqué",
                "verbose_name_plural": "Communiqués",
                "ordering": ["-publication_date"],
            },
        ),
    ]
