# Generated by Django 4.2.23 on 2025-07-13 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0016_alter_department_name_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookDigitization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Non commencé"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("published", "Publié"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("last_scanned_page", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.OneToOneField(
                        limit_choices_to={"is_digital": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digitization_process",
                        to="core.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digitalisation de Livre",
                "verbose_name_plural": "Digitalisations de Livres",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="NuboUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pin_code",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Code PIN Nubo",
                    ),
                ),
                (
                    "center",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nubo_user",
                        to="core.documentationcenter",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nubo_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur Nubo",
                "verbose_name_plural": "Utilisateurs Nubo",
            },
        ),
        migrations.CreateModel(
            name="DigitizedPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="nubo_scans/")),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "digitization_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="core.bookdigitization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Digitalisée",
                "verbose_name_plural": "Pages Digitalisées",
                "ordering": ["page_number"],
                "unique_together": {("digitization_process", "page_number")},
            },
        ),
    ]
