# Generated by Django 4.2.23 on 2025-07-13 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_bookdigitization_nubouser_digitizedpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NuboUser",
        ),
    ]
