# Generated by Django 4.2.7 on 2025-07-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix (Gourdes)",
            ),
        ),
    ]
