# Generated by Django 4.2.7 on 2025-07-27 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_add_price_to_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenreLitteraire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nom du Genre Littéraire",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Genre Littéraire",
                "verbose_name_plural": "Genres Littéraires",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SousGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du Sous-Genre"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_genres",
                        to="core.genrelitteraire",
                        verbose_name="Genre Littéraire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-Genre",
                "verbose_name_plural": "Sous-Genres",
                "ordering": ["genre__name", "name"],
                "unique_together": {("genre", "name")},
            },
        ),
        migrations.CreateModel(
            name="SousTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du Sous-Thème"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Sous-Thème",
                "verbose_name_plural": "Sous-Thèmes",
                "ordering": ["theme__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du Thème"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Thème",
                "verbose_name_plural": "Thèmes",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="soustheme",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sous_themes",
                to="core.theme",
                verbose_name="Thème Principal",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="genre_litteraire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.genrelitteraire",
                verbose_name="Genre Littéraire",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="sous_genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.sousgenre",
                verbose_name="Sous-Genre",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="sous_theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.soustheme",
                verbose_name="Sous-Thème",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.theme",
                verbose_name="Thème Principal",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="soustheme",
            unique_together={("theme", "name")},
        ),
    ]
