# Generated by Django 4.2.7 on 2025-07-27 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_genrelitteraire_sousgenre_soustheme_theme_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GenreLitteraire",
            new_name="LiteraryGenre",
        ),
        migrations.RenameModel(
            old_name="SousGenre",
            new_name="SubGenre",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="genre_litteraire",
            new_name="literary_genre",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="sous_genre",
            new_name="sub_genre",
        ),
    ]
