# Generated by Django 4.2.7 on 2025-07-27 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_rename_genrelitteraire_literarygenre_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="sous_theme",
            new_name="sub_theme",
        ),
    ]
