# Generated by Django 4.2.7 on 2025-07-27 14:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_rename_sous_theme_book_sub_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a cover image for the book (max. 5MB)",
                null=True,
                upload_to=core.models.Book.get_upload_path,
                verbose_name="Image de Couverture",
            ),
        ),
    ]
