# Generated by Django 4.2.7 on 2025-07-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_book_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="books/covers/",
                verbose_name="Image de Couverture",
            ),
        ),
    ]
