# Generated by Django 4.2.7 on 2025-07-27 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0028_alter_book_cover_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la Langue"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Code ISO"
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="Langue Favorite"),
                ),
            ],
            options={
                "verbose_name": "Langue",
                "verbose_name_plural": "Langues",
                "ordering": ["-is_favorite", "name"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="has_volumes",
            field=models.BooleanField(default=False, verbose_name="Possède des Tomes"),
        ),
        migrations.AddField(
            model_name="book",
            name="minimum_age_required",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Âge Minimum Requis"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="volume_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de Tomes"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="age_verified",
            field=models.BooleanField(default=False, verbose_name="Âge Vérifié"),
        ),
        migrations.AddField(
            model_name="loan",
            name="cancellation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'Annulation"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="cancellation_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notes d'Annulation"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("member_request", "Demande du membre"),
                    ("age_restriction", "Restriction d'âge"),
                    ("book_unavailable", "Livre indisponible"),
                    ("book_damaged", "Livre endommagé"),
                    ("policy_violation", "Violation des règles"),
                    ("other", "Autre raison"),
                ],
                max_length=50,
                null=True,
                verbose_name="Raison d'Annulation",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="member_age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Âge du Membre"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_loans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Traité par",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En Attente"),
                    ("approved", "Approuvé"),
                    ("borrowed", "Emprunté"),
                    ("returned", "Retourné"),
                    ("overdue", "En Retard"),
                    ("lost", "Perdu"),
                    ("cancelled", "Annulé"),
                    ("rejected", "Rejeté"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Statut du Prêt",
            ),
        ),
        migrations.CreateModel(
            name="DeletedBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_data", models.JSONField(verbose_name="Données du Livre")),
                (
                    "deletion_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Suppression"
                    ),
                ),
                (
                    "deletion_reason",
                    models.TextField(verbose_name="Raison de la Suppression"),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supprimé par",
                    ),
                ),
                (
                    "documentation_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.documentationcenter",
                        verbose_name="Centre de Documentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livre Supprimé",
                "verbose_name_plural": "Livres Supprimés",
                "ordering": ["-deletion_date"],
            },
        ),
        migrations.CreateModel(
            name="BookVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume_number",
                    models.PositiveIntegerField(verbose_name="Numéro du Tome"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre du Tome"),
                ),
                (
                    "quantity_available",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantité Disponible"
                    ),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantité Totale"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix (Gourdes)",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="books/volumes/covers/",
                        verbose_name="Image de Couverture",
                    ),
                ),
                (
                    "pages",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nombre de Pages"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="core.book",
                        verbose_name="Livre Principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tome/Volume",
                "verbose_name_plural": "Tomes/Volumes",
                "ordering": ["book__title", "volume_number"],
                "unique_together": {("book", "volume_number")},
            },
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Langue",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loans",
                to="core.bookvolume",
                verbose_name="Tome/Volume",
            ),
        ),
    ]
