# Generated by Django 4.2.7 on 2025-07-27 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_language_book_has_volumes_book_minimum_age_required_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="book",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="volume",
        ),
        migrations.AddField(
            model_name="loan",
            name="expected_return_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de Retour Attendue"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="form_creation_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Date de Création du Formulaire",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="return_remarks",
            field=models.TextField(
                blank=True, null=True, verbose_name="Remarques sur le Retour"
            ),
        ),
        migrations.CreateModel(
            name="LoanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_items",
                        to="core.book",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_items",
                        to="core.loan",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_items",
                        to="core.bookvolume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de Prêt",
                "verbose_name_plural": "Articles de Prêt",
                "unique_together": {("loan", "book", "volume")},
            },
        ),
    ]
