# Generated by Django 4.2.7 on 2025-07-27 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_remove_loan_book_remove_loan_volume_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="expected_return_date",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="form_creation_date",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="return_remarks",
        ),
        migrations.AddField(
            model_name="loan",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="core.book",
                verbose_name="Livre/Ouvrage",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loan",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loans",
                to="core.bookvolume",
                verbose_name="Tome/Volume",
            ),
        ),
        migrations.DeleteModel(
            name="LoanItem",
        ),
    ]
