# Generated by Django 4.2.7 on 2025-07-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_remove_loan_expected_return_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Quantité Empruntée"
            ),
        ),
    ]
