# Generated by Django 4.2.7 on 2025-07-31 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0032_loan_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="editor",
            field=models.CharField(blank=True, max_length=255, verbose_name="Éditeur"),
        ),
        migrations.AddField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.CreateModel(
            name="DeletionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(verbose_name="ID de l'objet"),
                ),
                (
                    "deletion_type",
                    models.CharField(
                        choices=[
                            ("book", "Livre/Ouvrage"),
                            ("member", "Membre"),
                            ("staff", "Personnel"),
                            ("loan", "Prêt"),
                            ("training", "Formation"),
                            ("document", "Document"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de suppression",
                    ),
                ),
                (
                    "item_identifier",
                    models.CharField(
                        help_text="Nom, titre ou identifiant unique de l'élément supprimé",
                        max_length=255,
                        verbose_name="Identifiant de l'élément",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Une explication détaillée de la raison de la suppression",
                        verbose_name="Justification de la suppression",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        help_text="Informations supplémentaires sur l'élément au moment de la suppression",
                        null=True,
                        verbose_name="Données supplémentaires",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Type de contenu",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supprimé par",
                    ),
                ),
                (
                    "documentation_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_logs",
                        to="core.documentationcenter",
                        verbose_name="Centre de Documentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal de Suppression",
                "verbose_name_plural": "Journaux de Suppression",
                "ordering": ["-deleted_at"],
                "indexes": [
                    models.Index(
                        fields=["documentation_center", "deleted_at"],
                        name="core_deleti_documen_f5842c_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_deleti_content_630a89_idx",
                    ),
                    models.Index(
                        fields=["deleted_by", "deleted_at"],
                        name="core_deleti_deleted_a34b02_idx",
                    ),
                ],
            },
        ),
    ]
