# Generated by Django 4.2.7 on 2025-08-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_book_editor_member_user_deletionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de Naissance"
            ),
        ),
    ]
