# Generated by Django 4.2.7 on 2025-08-03 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0034_member_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deletionlog",
            name="deletion_type",
            field=models.CharField(
                choices=[
                    ("book", "Livre"),
                    ("member", "Membre"),
                    ("staff", "Personnel"),
                    ("loan", "Prêt"),
                    ("training", "Formation"),
                    ("document", "Document"),
                    ("other", "Autre"),
                ],
                max_length=20,
                verbose_name="Type de suppression",
            ),
        ),
        migrations.AlterField(
            model_name="deletionlog",
            name="documentation_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deletion_logs",
                to="core.documentationcenter",
                verbose_name="Centre de Documentation",
            ),
        ),
        migrations.CreateModel(
            name="BookRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_by",
                        to="core.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books_read",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Livre Lu",
                "verbose_name_plural": "Livres Lus",
                "ordering": ["-created_at"],
                "unique_together": {("user", "book")},
            },
        ),
        migrations.CreateModel(
            name="BookLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="core.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Like de Livre",
                "verbose_name_plural": "Likes de Livres",
                "ordering": ["-created_at"],
                "unique_together": {("user", "book")},
            },
        ),
        migrations.CreateModel(
            name="BookDislike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dislikes",
                        to="core.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_dislikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dislike de Livre",
                "verbose_name_plural": "Dislikes de Livres",
                "ordering": ["-created_at"],
                "unique_together": {("user", "book")},
            },
        ),
    ]
