# Generated by Django 4.2.7 on 2025-08-03 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0035_alter_deletionlog_deletion_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communique",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this communique has been viewed"
            ),
        ),
        migrations.AddField(
            model_name="communique",
            name="viewers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have viewed this communique",
                related_name="viewed_communiques",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CommuniqueReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("like", "Like"), ("dislike", "Dislike")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "communique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="core.communique",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communique_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Communiqué Reaction",
                "verbose_name_plural": "Communiqué Reactions",
                "unique_together": {("user", "communique")},
            },
        ),
    ]
