# Generated by Django 4.2.23 on 2025-07-09 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.activity')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activities', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_assignments', to='core.staff')),
            ],
            options={
                'verbose_name': "Affectation d'Activité",
                'verbose_name_plural': "Affectations d'Activités",
                'ordering': ['-assigned_at'],
                'unique_together': {('activity', 'staff_member')},
            },
        ),
        migrations.CreateModel(
            name='ActivityStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('suspended', 'Suspendu'), ('restored', 'Restauré'), ('deleted', 'Supprimé'), ('completed', 'Terminé')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Raison du changement de statut', null=True, verbose_name='Raison')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='core.activity')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal de Statut d'Activité",
                'verbose_name_plural': "Journaux de Statut d'Activités",
                'ordering': ['-changed_at'],
            },
        ),
    ]
