# Generated by Django 4.2.23 on 2025-07-09 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_activityassignment_activitystatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('planned', 'Planifié'), ('active', 'Actif'), ('inactive', 'Inactif'), ('completed', 'Terminé'), ('suspended', 'Suspendu'), ('deleted', 'Supprimé')], default='planned', max_length=20, verbose_name='Statut'),
        ),
    ]
