# Generated by Django 4.2.7 on 2025-08-04 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0039_alter_activity_status_add_deleted_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="activitystatuslog",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("created", "Créé"),
                    ("updated", "Mis à jour"),
                    ("deleted", "Supprimé"),
                    ("suspended", "Suspendu"),
                    ("restored", "Restauré"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activitystatuslog",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="activitystatuslog",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ActivityGroupAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_assignments",
                        to="core.activity",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_activity_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_assignments",
                        to="auth.group",
                        verbose_name="Groupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation de Groupe à une Activité",
                "verbose_name_plural": "Affectations de Groupes aux Activités",
                "ordering": ["-assigned_at"],
                "unique_together": {("activity", "group")},
            },
        ),
    ]
