# Generated by Django 4.2.7 on 2025-08-04 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0041_activitygroupassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Créé"),
                            ("updated", "Mis à jour"),
                            ("deleted", "Supprimé"),
                            ("suspended", "Suspendu"),
                            ("restored", "Restauré"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal de Statut de Membre",
                "verbose_name_plural": "Journaux de Statut de Membres",
                "ordering": ["-changed_at"],
            },
        ),
    ]
