# Generated by Django 4.2.7 on 2025-08-04 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_memberstatuslog"),
    ]

    operations = []
