# Generated by Django 4.2.7 on 2025-08-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_auto_20250804_0455"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture_updated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Date de dernière modification de la photo de profil",
            ),
        ),
    ]
