# Generated by Django 4.2.7 on 2025-08-06 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0044_profile_profile_picture_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberActivityAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_assignments",
                        to="core.activity",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_member_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_assignments",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation de Membre à une Activité",
                "verbose_name_plural": "Affectations de Membres aux Activités",
                "ordering": ["-assigned_at"],
                "unique_together": {("activity", "member")},
            },
        ),
    ]
