# Generated by Django 4.2.7 on 2025-08-06 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0045_memberactivityassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du dossier"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="document_folders/covers/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("confidential", "Confidentiel"),
                        ],
                        default="confidential",
                        max_length=20,
                        verbose_name="Niveau de confidentialité",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "minimum_age",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Âge minimum requis pour accéder à ce dossier (0 = aucune restriction)",
                        verbose_name="Âge minimum requis",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_folders",
                        to="core.activity",
                        verbose_name="Activité associée",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_document_folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "documentation_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_folders",
                        to="core.documentationcenter",
                        verbose_name="Centre de Documentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier de Documents",
                "verbose_name_plural": "Dossiers de Documents",
                "ordering": ["-created_at"],
                "unique_together": {("documentation_center", "name")},
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du document"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(upload_to="documents/", verbose_name="Fichier"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="documents/covers/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date du document"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Type de fichier"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Taille du fichier (octets)"
                    ),
                ),
                (
                    "override_folder_settings",
                    models.BooleanField(
                        default=False,
                        help_text="Si activé, les paramètres de confidentialité spécifiques à ce document seront utilisés",
                        verbose_name="Remplacer les paramètres du dossier",
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("confidential", "Confidentiel"),
                        ],
                        default="confidential",
                        max_length=20,
                        verbose_name="Niveau de confidentialité",
                    ),
                ),
                (
                    "minimum_age",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Âge minimum requis pour accéder à ce document (0 = aucune restriction)",
                        verbose_name="Âge minimum requis",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.documentfolder",
                        verbose_name="Dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
