# Generated by Django 4.2.7 on 2025-08-03 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0036_communique_view_count_communique_viewers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeVerificationFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de la tentative",
                    ),
                ),
                (
                    "member_age",
                    models.PositiveIntegerField(
                        verbose_name="Âge du Membre au moment de la tentative"
                    ),
                ),
                (
                    "required_age",
                    models.PositiveIntegerField(
                        verbose_name="Âge minimum requis pour le livre"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_verification_failures",
                        to="core.book",
                        verbose_name="Livre/Ouvrage",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_verification_failures",
                        to="core.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Échec de vérification d'âge",
                "verbose_name_plural": "Échecs de vérification d'âge",
                "ordering": ["-attempted_at"],
                "unique_together": {("member", "book", "attempted_at")},
            },
        ),
    ]
