# Generated by Django 4.2.7 on 2025-08-03 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0036_communique_view_count_communique_viewers_and_more'),
        ('center_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone1', models.CharField(max_length=20, verbose_name='Téléphone 1')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Téléphone 2')),
                ('request', models.TextField(verbose_name='Requête')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Est résolue')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notes de résolution')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('documentation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documentationcenter', verbose_name='Centre de documentation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
            ],
            options={
                'verbose_name': 'Doléance',
                'verbose_name_plural': 'Doléances',
                'ordering': ['-created_at'],
            },
        ),
    ]
