# Generated by Django 4.2.7 on 2025-08-03 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0037_chatmessage"),
        ("center_panel", "0002_complaint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="documentation_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="core.documentationcenter",
                verbose_name="Centre de Documentation",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="is_resolved",
            field=models.BooleanField(default=False, verbose_name="Résolu"),
        ),
    ]
